/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Theapplication;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Stephen Matara
 */
public class SGRWEB extends javax.swing.JFrame {

    /**
     * Creates new form SGRWEB
     */
   DbConnection conn=new DbConnection();
    public SGRWEB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        customerdetails = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lblpassengername = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        txtidno = new javax.swing.JTextField();
        lblhudumano = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtphoneno = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsurname = new javax.swing.JTextField();
        lbladdress = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        btnreset1 = new javax.swing.JButton();
        traveltype = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rbtnlowclass = new javax.swing.JRadioButton();
        rbtnmediumclass = new javax.swing.JRadioButton();
        rbtnhighclass = new javax.swing.JRadioButton();
        rbtnreturn = new javax.swing.JRadioButton();
        rbtnsingle = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rbtnyea = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        rbtnyes = new javax.swing.JRadioButton();
        btnreset2 = new javax.swing.JButton();
        totalcosts = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        rbtnluggage = new javax.swing.JRadioButton();
        rbtndistance = new javax.swing.JRadioButton();
        txtaccomodation = new javax.swing.JComboBox<>();
        lblaccomodation = new javax.swing.JLabel();
        rbtntraintaxpaid = new javax.swing.JRadioButton();
        rbtninsurance = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtto = new javax.swing.JComboBox<>();
        txtfrom = new javax.swing.JComboBox<>();
        lbldestination = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        btnbooknow = new javax.swing.JButton();
        btntotal = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtaccomo = new javax.swing.JTextField();
        txttravel = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        btnreset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        reports = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnreset3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        REPORTTABLE = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel4.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 48)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/logo.png"))); // NOI18N
        jLabel4.setText("SGR TRAVELLING RESERVATION SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1178, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        customerdetails.setBackground(new java.awt.Color(255, 204, 102));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        lblpassengername.setFont(new java.awt.Font("Yu Gothic", 2, 11)); // NOI18N
        lblpassengername.setText("FIRSTNAME");

        txtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfirstnameActionPerformed(evt);
            }
        });

        lblhudumano.setFont(new java.awt.Font("Yu Gothic", 2, 11)); // NOI18N
        lblhudumano.setText("ID/P NO");

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 2, 11)); // NOI18N
        jLabel5.setText("EMAIL ADRESS");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 2, 11)); // NOI18N
        jLabel1.setText("PHONE NO");

        txtphoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphonenoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 2, 11)); // NOI18N
        jLabel6.setText("SURNAME");

        txtsurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsurnameActionPerformed(evt);
            }
        });

        lbladdress.setFont(new java.awt.Font("Yu Gothic", 2, 11)); // NOI18N
        lbladdress.setText("ADDRESS");

        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblpassengername, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhudumano, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbladdress, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtaddress)
                    .addComponent(txtsurname)
                    .addComponent(txtidno)
                    .addComponent(txtfirstname)
                    .addComponent(txtphoneno)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassengername)
                    .addComponent(txtfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtsurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbladdress))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblhudumano))
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(21, 21, 21))
        );

        btnreset1.setBackground(new java.awt.Color(255, 153, 51));
        btnreset1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_available_updates_20px_1.png"))); // NOI18N
        btnreset1.setText("Reset");
        btnreset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout customerdetailsLayout = new javax.swing.GroupLayout(customerdetails);
        customerdetails.setLayout(customerdetailsLayout);
        customerdetailsLayout.setHorizontalGroup(
            customerdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerdetailsLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnreset1)
                .addGap(0, 728, Short.MAX_VALUE))
        );
        customerdetailsLayout.setVerticalGroup(
            customerdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerdetailsLayout.createSequentialGroup()
                .addGroup(customerdetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerdetailsLayout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(btnreset1))
                    .addGroup(customerdetailsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CUSTOMER DETAILS", customerdetails);

        traveltype.setBackground(new java.awt.Color(255, 204, 102));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("CLASS");

        rbtnlowclass.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        rbtnlowclass.setText("LOW CLASS");

        rbtnmediumclass.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        rbtnmediumclass.setText("MEDIUM CLASS");
        rbtnmediumclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnmediumclassActionPerformed(evt);
            }
        });

        rbtnhighclass.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        rbtnhighclass.setText("HIGH CLASS");

        rbtnreturn.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        rbtnreturn.setText("RETURN");
        rbtnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnreturnActionPerformed(evt);
            }
        });

        rbtnsingle.setText("SINGLE");
        rbtnsingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnsingleActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("TICKET");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("CHILD");

        rbtnyea.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        rbtnyea.setText("YES");
        rbtnyea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnyeaActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("ADULT");

        rbtnyes.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        rbtnyes.setText("YES");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(rbtnmediumclass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel7))
                            .addComponent(rbtnlowclass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbtnyes, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(45, 45, 45)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel8))
                            .addComponent(rbtnreturn))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnyea)
                            .addComponent(jLabel9)))
                    .addComponent(rbtnsingle))
                .addGap(33, 33, 33))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(rbtnhighclass)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnyes)
                    .addComponent(rbtnsingle)
                    .addComponent(rbtnlowclass)
                    .addComponent(rbtnyea))
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnreturn)
                    .addComponent(rbtnmediumclass))
                .addGap(18, 18, 18)
                .addComponent(rbtnhighclass)
                .addGap(13, 13, 13))
        );

        btnreset2.setBackground(new java.awt.Color(255, 153, 51));
        btnreset2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_available_updates_20px_1.png"))); // NOI18N
        btnreset2.setText("Reset");
        btnreset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout traveltypeLayout = new javax.swing.GroupLayout(traveltype);
        traveltype.setLayout(traveltypeLayout);
        traveltypeLayout.setHorizontalGroup(
            traveltypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(traveltypeLayout.createSequentialGroup()
                .addGroup(traveltypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(traveltypeLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(traveltypeLayout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(btnreset2)))
                .addContainerGap(766, Short.MAX_VALUE))
        );
        traveltypeLayout.setVerticalGroup(
            traveltypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(traveltypeLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnreset2)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("TRAVEL TYPE", traveltype);

        totalcosts.setBackground(new java.awt.Color(255, 204, 102));

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        rbtnluggage.setText("Luggage Exit");

        rbtndistance.setText("Distance over 2000km");
        rbtndistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtndistanceActionPerformed(evt);
            }
        });

        txtaccomodation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "SINGLE", "DOUBLE" }));

        lblaccomodation.setFont(new java.awt.Font("Yu Gothic", 2, 11)); // NOI18N
        lblaccomodation.setText("ACCOMMODATION");

        rbtntraintaxpaid.setText("Train tax paid");

        rbtninsurance.setText("Travelling Insurance paid");

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 2, 11)); // NOI18N
        jLabel3.setText("TO");

        txtto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", " NAKURU", "NAIVAISHA", "NAIROBI", "LAMU", " KILIFI", "MOMBASA " }));

        txtfrom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "NAKURU", "NAIVAISHA", "NAIROBI", "LAMU", "KILIFI", "MOMBASA", " ", " ", " " }));
        txtfrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfromActionPerformed(evt);
            }
        });

        lbldestination.setFont(new java.awt.Font("Yu Gothic", 2, 11)); // NOI18N
        lbldestination.setText("FROM");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(txtto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(lbldestination, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(lblaccomodation, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtaccomodation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtninsurance)
                            .addComponent(rbtntraintaxpaid))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtndistance)
                            .addComponent(rbtnluggage))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldestination))
                .addGap(27, 27, 27)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblaccomodation)
                    .addComponent(txtaccomodation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtntraintaxpaid)
                    .addComponent(rbtndistance))
                .addGap(36, 36, 36)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtninsurance)
                    .addComponent(rbtnluggage))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        btnbooknow.setBackground(new java.awt.Color(255, 153, 51));
        btnbooknow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_ticket_20px.png"))); // NOI18N
        btnbooknow.setText("Book Now");
        btnbooknow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbooknowActionPerformed(evt);
            }
        });

        btntotal.setBackground(new java.awt.Color(255, 102, 255));
        btntotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_plus_math_20px.png"))); // NOI18N
        btntotal.setText("Total");
        btntotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalActionPerformed(evt);
            }
        });

        jLabel11.setText("Accomodation cost");

        jLabel12.setText("Travelling cost");

        txtaccomo.setEditable(false);

        txttravel.setEditable(false);

        txttotal.setEditable(false);

        btnreset.setBackground(new java.awt.Color(255, 153, 51));
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_available_updates_20px_1.png"))); // NOI18N
        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        jLabel2.setText("Click total to find your total cost");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnreset)
                        .addGap(157, 157, 157)
                        .addComponent(btnbooknow))
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(btntotal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12))
                            .addGap(109, 109, 109)
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txttravel, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(txtaccomo))))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtaccomo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txttravel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btntotal))
                .addGap(89, 89, 89)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreset)
                    .addComponent(btnbooknow))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout totalcostsLayout = new javax.swing.GroupLayout(totalcosts);
        totalcosts.setLayout(totalcostsLayout);
        totalcostsLayout.setHorizontalGroup(
            totalcostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalcostsLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 234, Short.MAX_VALUE))
        );
        totalcostsLayout.setVerticalGroup(
            totalcostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalcostsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totalcostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("TOTAL COSTS", totalcosts);

        reports.setBackground(new java.awt.Color(255, 204, 102));

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel9.setPreferredSize(new java.awt.Dimension(400, 400));

        area.setEditable(false);
        area.setColumns(20);
        area.setRows(5);
        jScrollPane2.setViewportView(area);

        jButton3.setBackground(new java.awt.Color(255, 0, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_print_30px.png"))); // NOI18N
        jButton3.setText("Print Receipt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 0, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_receipt_30px.png"))); // NOI18N
        jButton1.setText("Generate Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnreset3.setBackground(new java.awt.Color(255, 153, 51));
        btnreset3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_available_updates_20px_1.png"))); // NOI18N
        btnreset3.setText("Reset");
        btnreset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreset3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnreset3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnreset3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        REPORTTABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First name", "surname", "address", "email", "from", "accomodation", "idno", "tel no", "to"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(REPORTTABLE);

        jButton4.setBackground(new java.awt.Color(255, 0, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_preview_pane_20px.png"))); // NOI18N
        jButton4.setText("Retrieve Data");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 0, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_restart_20px_1.png"))); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/icons8_delete_20px.png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout reportsLayout = new javax.swing.GroupLayout(reports);
        reports.setLayout(reportsLayout);
        reportsLayout.setHorizontalGroup(
            reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(reportsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(reportsLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jButton4)
                        .addGap(78, 78, 78)
                        .addComponent(jButton2)
                        .addGap(74, 74, 74)
                        .addComponent(jButton5)
                        .addContainerGap(144, Short.MAX_VALUE))))
        );
        reportsLayout.setVerticalGroup(
            reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reportsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addGroup(reportsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(reportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("REPORTS", reports);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtsurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsurnameActionPerformed

    private void txtphonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphonenoActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfirstnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        area.setText("**************************************************\n\n");
        area.setText(area.getText()+"*                        RECEIPT              *\n\n");
        area.setText(area.getText()+"****************************************************\n\n");

        Calendar calendar = Calendar.getInstance();
        calendar.getTime();

        SimpleDateFormat tTime = new SimpleDateFormat(" HH:mm:ss");
        String iTime=(tTime.format(calendar.getTime()));

        SimpleDateFormat Tdate = new SimpleDateFormat(" dd-MM-yyyy");
        String iDate=(Tdate.format(calendar.getTime()));

        area.setText(area.getText()+"             Time:"+iTime+"  Date:"+iDate+"\n\n");
        area.setText(area.getText()+"FIRST NAME:"+txtfirstname.getText()+"\n\n");
        area.setText(area.getText()+"SURNAME :"+txtsurname.getText()+"\n\n");
        area.setText(area.getText()+"FROM :"+txtfrom.getSelectedItem().toString()+"\n\n");
        area.setText(area.getText()+"TO :"+txtto.getSelectedItem().toString()+"\n\n");
        area.setText(area.getText()+"Accomodation :"+txtaccomodation.getSelectedItem().toString()+"\n\n");
        area.setText(area.getText()+"ID/P NO :"+txtidno.getText()+"\n\n");
        area.setText(area.getText()+"Address :"+txtaddress.getText()+"\n\n");
        area.setText(area.getText()+"EMAIL ADDRESS :"+txtemail.getText()+"\n\n");
        area.setText(area.getText()+"PHONE NO :"+txtphoneno.getText()+"\n\n");
        area.setText(area.getText()+"****************************************************\n\n");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try{

            area.print();
        }
        catch(Exception ex){

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnbooknowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbooknowActionPerformed
        // TODO add your handling code here:
        String firstname=txtfirstname.getText();
        String surname=txtsurname.getText();
        String address=txtaddress.getText();
        String idpno=txtidno.getText();
        String email=txtemail.getText();
        String phoneno=txtphoneno.getText();
        String from=txtfrom.getSelectedItem().toString();
        String to=txtto.getSelectedItem().toString();
        String accomodation=txtaccomodation.getSelectedItem().toString();
        String  total=txttotal.getText();

        conn.inserttobooking(firstname, surname, address,idpno,email,phoneno,from,to,accomodation,total);
    }//GEN-LAST:event_btnbooknowActionPerformed

    private void txtfromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfromActionPerformed

    private void rbtndistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtndistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtndistanceActionPerformed

    private void rbtnyeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnyeaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnyeaActionPerformed

    private void rbtnsingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnsingleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnsingleActionPerformed

    private void rbtnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnreturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnreturnActionPerformed

    private void rbtnmediumclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnmediumclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnmediumclassActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
       String firstname=txtfirstname.getText();
        String surname=txtsurname.getText();
        String address=txtaddress.getText();
        String idpno=txtidno.getText();
        String email=txtemail.getText();
        String phoneno=txtphoneno.getText();
        String from=txtfrom.getSelectedItem().toString();
        String to=txtto.getSelectedItem().toString();
        String accomodation=txtaccomodation.getSelectedItem().toString();
        String  total=txttotal.getText();
        
        conn.updatebooking(firstname,surname,address,idpno,email,phoneno,from,to,accomodation,total);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         ResultSet newrs=conn.getbookings();
        try
        {
            DefaultTableModel newmodel=(DefaultTableModel)REPORTTABLE.getModel();
            
            while(newrs.next()){
                Vector <String>bookingitems=new Vector<String>();
                bookingitems.add(newrs.getString("firstname"));
                bookingitems.add(newrs.getString("surname"));
                bookingitems.add(newrs.getString("address"));
                bookingitems.add(newrs.getString("email"));
                bookingitems.add(newrs.getString("startfrom"));
                bookingitems.add(newrs.getString("accomodation"));
                bookingitems.add(newrs.getString("idpno"));
                bookingitems.add(newrs.getString("phoneno"));
                bookingitems.add(newrs.getString("destination"));
                
                
              
                newmodel.addRow(bookingitems);
             new SimpleReport(newmodel);
            }
                
                }
        catch(SQLException x){
            JOptionPane.showMessageDialog(null, x.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String idpno=txtidno.getText();
        
        conn.deletebooking(idpno);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btntotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalActionPerformed
        // TODO add your handling code here:
        
        
        
                                                
       
       
        
double NAKURU  =5000 ; 
double NAIVAISHA =4000;
double NAIROBI =3000 ;  
double LAMU  =5000;
double KILIFI =2000;
double MOMBASA =7000;
        double acc_Single=1500;
        double acc_double=2500;
        double[] TravelCost=new double[15];
        if((txtto.getSelectedItem().equals("NAKURU"))&&txtaccomodation.getSelectedItem().equals("SINGLE")){
            TravelCost[0]=NAKURU;
            TravelCost[1]=acc_Single;

            TravelCost[2]=NAKURU+acc_Single;
            String TRAVEL=String.format("Ksh%.2f",TravelCost[0]);
            String ACCOMODATE=String.format("Ksh%.2f",TravelCost[1]);

            String TOTAL=String.format("Ksh%.2f",TravelCost[2]);
            txttotal.setText(TOTAL);
            txttravel.setText(TRAVEL);
            txtaccomo.setText(ACCOMODATE);
         
        }
       else if((txtto.getSelectedItem().equals("NAKURU"))&&txtaccomodation.getSelectedItem().equals("DOUBLE")){
           TravelCost[0]=NAKURU;
           TravelCost[1]=acc_double;
            TravelCost[2]=NAKURU+acc_double;
            String TOTAL=String.format("Ksh%.2f",TravelCost[2]);
             String TRAVEL=String.format("Ksh%.2f",TravelCost[0]);
            String ACCOMODATE=String.format("Ksh%.2f",TravelCost[1]);


            txttotal.setText(TOTAL);
            txttravel.setText(TRAVEL);
            txtaccomo.setText(ACCOMODATE);
        }
       else if((txtto.getSelectedItem().equals("NAIVAISHA"))&&txtaccomodation.getSelectedItem().equals("SINGLE")){
           TravelCost[0]=NAIVAISHA;
           TravelCost[1]=acc_Single;
            TravelCost[2]=NAIVAISHA+acc_Single;
            String TOTAL=String.format("Ksh%.2f",TravelCost[2]);
            String TRAVEL=String.format("Ksh%.2f",TravelCost[0]);
            String ACCOMODATE=String.format("Ksh%.2f",TravelCost[1]);


            txttotal.setText(TOTAL);
            txttravel.setText(TRAVEL);
            txtaccomo.setText(ACCOMODATE);
       }
       else if((txtto.getSelectedItem().equals("NAIVAISHA"))&&txtaccomodation.getSelectedItem().equals("DOUBLE")){
           TravelCost[0]=NAIVAISHA;
           TravelCost[1]=acc_double;
            TravelCost[2]=NAIVAISHA+acc_double;
            String TOTAL=String.format("Ksh%.2f" ,TravelCost[2]);
            String ACCOMODATE=String.format("Ksh%.2f ",TravelCost[1]);
            String TRAVEL=String.format("Ksh%.2f ",TravelCost[0]);


            txttotal.setText(TOTAL);
            txttravel.setText(TRAVEL);
            txtaccomo.setText(ACCOMODATE);
       } 
        else if((txtto.getSelectedItem().equals("MOMBASA"))&&txtaccomodation.getSelectedItem().equals("SINGLE")){
            TravelCost[0]=MOMBASA;
            TravelCost[1]=acc_Single;
            TravelCost[2]=MOMBASA+acc_Single;
            String TOTAL=String.format("Ksh%.2f",TravelCost[2]);
            String TRAVEL=String.format("Ksh%.2f",TravelCost[0]);
            String ACCOMODATE=String.format("Ksh%.2f",TravelCost[1]);


            txttotal.setText(TOTAL);
             txttravel.setText(TRAVEL);
            txtaccomo.setText(ACCOMODATE);
        }
        else if((txtto.getSelectedItem().equals("MOMBASA"))&&txtaccomodation.getSelectedItem().equals("DOUBLE")){
            TravelCost[2]=MOMBASA+acc_Single;
            TravelCost[0]=MOMBASA;
            TravelCost[1]=acc_double;
            
            String TOTAL=String.format("Ksh%.2f",TravelCost[2]);
           String TRAVEL=String.format("Ksh%.2f",TravelCost[0]);
            String ACCOMODATE=String.format("Ksh%.2f", TravelCost[1]);
            txttotal.setText(TOTAL);
             txttravel.setText(TRAVEL);
            txtaccomo.setText(ACCOMODATE);
        }
        else if((txtto.getSelectedItem().equals("LAMU"))&&txtaccomodation.getSelectedItem().equals("SINGLE")){
            TravelCost[2]=LAMU+acc_Single;
             TravelCost[0]=LAMU;
            TravelCost[1]=acc_Single;
            String TOTAL=String.format("Ksh%.2f",TravelCost[2]);
            String TRAVEL=String.format("Ksh%.2f",TravelCost[0]);
            String ACCOMODATE=String.format("Ksh%.2f", TravelCost[1]);
            txttotal.setText(TOTAL);
            txttravel.setText(TRAVEL);
            txtaccomo.setText(ACCOMODATE);
        }
        else if((txtto.getSelectedItem().equals("LAMU"))&&txtaccomodation.getSelectedItem().equals("DOUBLE")){
            TravelCost[2]=LAMU+acc_double;
             TravelCost[0]=LAMU;
            TravelCost[1]=acc_double;
            String TOTAL=String.format("Ksh%.2f",TravelCost[2]); 
            String TRAVEL=String.format("Ksh%.2f",TravelCost[0]);
            String ACCOMODATE=String.format("Ksh%.2f", TravelCost[1]);
            
            
            
            
            txttotal.setText(TOTAL);
            txttravel.setText(TRAVEL);
            txtaccomo.setText(ACCOMODATE);
            
        }
    }//GEN-LAST:event_btntotalActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
         
        txtfrom.setSelectedItem("NONE");
        txtto.setSelectedItem("NONE");
        txtaccomodation.setSelectedItem("NONE");
        rbtndistance.setSelected(false);
        rbtnluggage.setSelected(false);
        rbtninsurance.setSelected(false);
        rbtntraintaxpaid.setSelected(false);
        txtaccomo.setText(null);
        txttravel.setText(null);
        txttotal.setText(null);
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnreset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset1ActionPerformed
        // TODO add your handling code here:
        txtfirstname.setText(null);
        txtsurname.setText(null);
        txtaddress.setText(null);
         txtidno.setText(null);
           txtemail.setText(null);
          txtphoneno.setText(null);
    }//GEN-LAST:event_btnreset1ActionPerformed

    private void btnreset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset2ActionPerformed
        // TODO add your handling code here:
         rbtnyes.setSelected(false);
          rbtnyea.setSelected(false);
        rbtnsingle.setSelected(false);
        rbtnreturn.setSelected(false);
        rbtnlowclass.setSelected(false);
        rbtnmediumclass.setSelected(false);
        rbtnhighclass.setSelected(false);
    }//GEN-LAST:event_btnreset2ActionPerformed

    private void btnreset3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreset3ActionPerformed
        // TODO add your handling code here:
        area.setText(null);
    }//GEN-LAST:event_btnreset3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SGRWEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SGRWEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SGRWEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SGRWEB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SGRWEB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable REPORTTABLE;
    private javax.swing.JTextArea area;
    private javax.swing.JButton btnbooknow;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnreset1;
    private javax.swing.JButton btnreset2;
    private javax.swing.JButton btnreset3;
    private javax.swing.JButton btntotal;
    private javax.swing.JPanel customerdetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblaccomodation;
    private javax.swing.JLabel lbladdress;
    private javax.swing.JLabel lbldestination;
    private javax.swing.JLabel lblhudumano;
    private javax.swing.JLabel lblpassengername;
    private javax.swing.JRadioButton rbtndistance;
    private javax.swing.JRadioButton rbtnhighclass;
    private javax.swing.JRadioButton rbtninsurance;
    private javax.swing.JRadioButton rbtnlowclass;
    private javax.swing.JRadioButton rbtnluggage;
    private javax.swing.JRadioButton rbtnmediumclass;
    private javax.swing.JRadioButton rbtnreturn;
    private javax.swing.JRadioButton rbtnsingle;
    private javax.swing.JRadioButton rbtntraintaxpaid;
    private javax.swing.JRadioButton rbtnyea;
    private javax.swing.JRadioButton rbtnyes;
    private javax.swing.JPanel reports;
    private javax.swing.JPanel totalcosts;
    private javax.swing.JPanel traveltype;
    private javax.swing.JTextField txtaccomo;
    private javax.swing.JComboBox<String> txtaccomodation;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JComboBox<String> txtfrom;
    private javax.swing.JTextField txtidno;
    private javax.swing.JTextField txtphoneno;
    private javax.swing.JTextField txtsurname;
    private javax.swing.JComboBox<String> txtto;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txttravel;
    // End of variables declaration//GEN-END:variables
}
